services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ayacoo\NewsTldr\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/Form/*'
